# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginRegistration', '0003_friend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='friend',
            new_name='user',
        ),
    ]
