# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginRegistration', '0004_auto_20170428_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_users', to='loginRegistration.User')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_users', to='loginRegistration.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='friend',
            name='user',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='_user_friends_+', through='loginRegistration.FriendRelationship', to='loginRegistration.User'),
        ),
        migrations.AlterUniqueTogether(
            name='friendrelationship',
            unique_together=set([('from_user', 'to_user')]),
        ),
    ]
